# Github Actions CI/CD
---

name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
       
      - name: Check Out - pull repository code
        uses: actions/checkout@v2

      - name: Run Test-Code
        run: docker-compose run --rm app sh -c 'python manage.py wait_for_dpython manage.py test'

      # - name: Run Flake8 for Lint Check
      #   run: docker-compose run --rm app sh -c 'flake8'
